### ISSUE TITLE
이거 왜 9 안나와요?

### ISSUE THREAD

**Issue by kampores** [pl-Steve28-lq/Num2Kor#1]
numToKor(9)

''

**Comment by kampores** [comment]
구(九),9 와 구(溝), 10^32 가 발음이 같아서 '구' 가 걸러지니 버그 수정 하세요. 일단 편법으로 쓰실 분들은 아래와 같이 쓰시면 됩니다.

Num2Kor/num2kor/num2kor.py / line 48
    # unit = [''] + list("만억조경해자양구간정재극")
    unit = [''] + list("만억조경해자양")

**Comment by pl-Steve28-lq** [comment]
수정하였습니다
